version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: nexa
      POSTGRES_PASSWORD: nexa
      POSTGRES_DB: nexa
    ports: [ "5432:5432" ]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg://nexa:nexa@db:5432/nexa
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_ORIGIN: http://localhost:3000
    ports: [ "8000:8000" ]
    depends_on: [ db ]
  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    ports: [ "3000:3000" ]
    depends_on: [ backend ]
volumes:
  pgdata:
