services:
  - type: web
    name: nexa-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///./nexa.db"
      - key: OPENAI_API_KEY
        value: "SET_IN_RENDER"
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_ORIGIN
        value: "*"

  - type: web
    name: nexa-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        value: "https://REPLACE_WITH_BACKEND_URL"
