services:
  - type: web
    name: nexa-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nexa-db
          property: connectionString
      - key: OPENAI_API_KEY        # la completarás en el panel al crear el Blueprint
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_ORIGIN
        value: "*"                 # tras el primer deploy, cámbiala por la URL del frontend

  - type: web
    name: nexa-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        value: "https://placeholder.example.com"  # luego la reemplazas por la URL del backend y redeploy

databases:
  - name: nexa-db
    databaseName: nexa
    user: nexa
